### ISSUE TITLE
Unable to re-position the window and hide toolbar

### ISSUE THREAD

**Issue by smolinacadena** [ayamadori/AlwaysOnTop#1]
Today the app updated to the latest version. I'm unable to move the window across the screen, usually I move the mini-view window to the lower-right corner of the screen.

Also, the address bar shows all the time in mini-view. Could there be an option to hide the toolbar? Previous version only had a back button in the title bar and that worked great.

**Comment by ayamadori** [comment]
You can move the window by dragging the titlebar.
Titlebar hides when the content in website (e.g. video) become fullscreen.

**Comment by ayamadori** [comment]
I understood your issue. 
You can re-position when touch only text area in the titlebar.
I will fix in next update.

**Comment by ayamadori** [comment]
https://github.com/ayamadori/AlwaysOnTop/commit/fbb1d6b15bd96b5e1afdb3585580aa43b53b44e9
