### ISSUE TITLE
There is audio and video synchronization problems

### ISSUE THREAD

**Issue by alialtun14** [ayamadori/AlwaysOnTop#2]
There is audio and video synchronization problems at first 30 seconds when a video is started.

To test this problem, following link can be used. 
https://www.ted.com/talks/olutimehin_adegbeye_who_belongs_in_a_city

**Comment by ayamadori** [comment]
Hmm... In my PC, the problem does not seem to be found.
Please try to play video after the loading finished.
(i.e. The loading indicator overwritten on Refresh button is hidden.)

**Comment by alialtun14** [comment]
Upon your recommendation, I waited until the loading of the video finished. But the result has not been changed for me. 

![start](https://user-images.githubusercontent.com/782196/44007704-6bb81e40-9e9a-11e8-9302-a3cfd3cef050.png)

**Comment by ayamadori** [comment]
I could reproduce the issue.
Especially, the issue seems to be found with subtitle.
Same issue is also found on Microsoft Edge that use the same web engine as this app.
(Different from Chrome browser)
So, I recommend you to feedback to TED or Microsoft.

**Comment by alialtun14** [comment]
I made feedback to Edge and TED for this issue. 

Thanks.

**Comment by alialtun14** [comment]
Incoming reply from TED.

Hello!
Thank you for reporting a problem with TED videos on Edge.

We've learned that users on the Windows operating system have experienced problems due to an incompatibility with our TED.com video player. As an alternative, we encourage you to visit this lower-bandwidth version of the site:

https://en.tiny.ted.com/talks/

Or, this embedded version: https://embed.ted.com/talks/

If neither option solves the synchronization problem, I recommend that you download TED videos and try playing them in an offline media player instead. Here's how to do that:

- Visit the page of the talk on TED.com
- Click the “Share” button on the right side of the video player
- In the window that appears, click the "Subtitles: Off" button to find a list of subtitles.
- Choose your preferred language (if applicable)
- Click 'Download video' 

Please let me know if this helped you view the videos without the problem. Thank you!

Warmest regards,
Jamey
TED Community Support Specialist
